
name: compilation test on push in main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  compilation_test:
    name: compilation test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install python
        run: sudo apt-get install build-essential python3 -y
      - name: install rust
        run: curl --proto '=https' --tlsv1.3 https://sh.rustup.rs -sSf | sh -s -- -y
      - name: run compilation tests
        run: make test
